thefrontside/effectionx

- task-buffer/task-buffer.ts
`TaskBuffer` does not have typedoc to guide usage in the IDE.
Add just enough to be helpful with intelli-sense, but not too much to be annoying.
> 📝 Add typedocs to the `TaskBuffer` type and supporting functions

- task-buffer/task-buffer.test.ts
One of the things you can do with a task buffer is `yield*` to it. This will await any pending tasks in the buffer before returning. If any of them fails, the drain will also fail. We have this functionality, but no test case.
Add a test.
> ✅ Add test for draining a task buffer

- www/deno.json
- www/routes/app.html.tsx
Deno Deploy is failing because it couldn't resolve the path to `@effection-contrib/deno-deploy`.
Don't use `file://` prefix.
> Fixed the path

- task-buffer/task-buffer.test.ts
- task-buffer/task-buffer.ts
I needed the Task Buffer to track FS write operations, but I needed it in V4. 
1. The Result type is not exported from V4, so I used V3
2. Replaced action with withResolvers
3. Move `sleep(0)` to iterable to give a bit of time between iterations
> Upgraded task-buffer to V4

- websocket/README.md
- websocket/websocket.ts
Get a good JSR score
JSR requires you to have code examples in your README or module doc in order to get a good score, so this adds the very basic usage, and also ignores the `WebSocketData` type since it is an alias and code editors will expand it to its actual type in intelligence.
> 📄 Add examples to README

- websocket/README.md
- www/assets/prism-atom-one-dark.css
- www/components/api.tsx
- www/components/rehype.tsx
- www/hooks/use-description-parse.tsx
- www/hooks/use-mdx.tsx
- www/hooks/use-package.tsx
- www/lib/remove-description-hr.ts
- www/lib/trim-after-hr.ts
- www/main.ts
When the readme has a long description, we need a way to separate the description from the main body of the README. Previously, it would default to a max length which didn't always make sense. 
Created a simple plugin to use before <rh> as a description.
> Made it possible to specify description with --- block

- .github/workflows/verify.yaml
- deno.json
- jsonl-store/README.md
- jsonl-store/context.test.ts
- jsonl-store/context.ts
- jsonl-store/deno.json
- jsonl-store/jsonl.test.ts
- jsonl-store/jsonl.ts
- jsonl-store/mod.ts
- jsonl-store/types.ts
- www/hooks/use-package.tsx
- www/main.ts
It's useful to organize data into JSONL files on the file system. I'm introducing JSONL Store, which allows me to store the content from external sources as files on the file system.
> Introducing JSONL Store

- .github/workflows/publish.yaml
Some of the packages were not tagged correctly in npm because we were tagging them with next.
Explicitly tag with latest.
> Make sure npm packages are tagged with latest

- jsonl-store/jsonl.test.ts
- jsonl-store/jsonl.ts
jsonl-store failed to publish to JSR because it had a package from deno.land. 
Fixing it sent me down a rabbit hole, but the outcome was useful. I found out that the package that I was using was actually published to NPM as `jsonlines-web` but it was also integrated into `jsr:@std/streaming` and `jsr:@std/json`. 
I was able to replace the dependency with `@std` packages. 
I also added a workflow that checks which directories were changed and runs the JSR publish dry-run command to test if it'll actually publish.
> Eliminated jsonlines dependency in favour of built in types

- www/main.ts
- www/routes/package.tsx
The /sitemap.xml was broken, which is a critical component for static site generation, both for this site.
It turns out that the `pkg.workspace` field was in the form of a relative path specifier which causes an error when you try and substitute it in for the `/:workspace` route.
This removes the string `"./"` from the front of any substitution.
> 🐛 Fix contrib sitemap

- .github/workflows/publish.yaml
We want `effection-contrib` maintainers to be able to commit without having to be members of `effection-contrib` scope on JSR. We can do this by using Frontside Jack's JSR token.  
Passing token to `deno publish`.
> Use JSR token to publish

- tinyexec/deno.json
- tinyexec/tinyexec.ts
Made Tinyexec dependency explicit in code to make code more easily copy and pastable.
Added it explicitely
> added missing dependency information

- fx/parallel.ts
- fx/race.ts
- fx/request.ts
- fx/safe.ts
There were some linting errors that were causing our tests to fail.
I fixed where I could, but wasn't sure what to do with the `any` casts, so I marked them as ignored. The fixes I applied required some formatting fixes.
> 🚨 fix linting errors

- tinyexec/README.md
- tinyexec/tinyexec.ts
Docs are good if we want a contrib library to have a good score and be used.
This adds typedocs for the tinyexec package as well as some simple examples
> 📝 add api docs and readme examples for tinyexec

- task-buffer/deno.json
- task-buffer/task-buffer.ts
I want to replace task buffer in staticalize with the version from effection-contrib, but I need to upgrade it to v4.
* Using v4 from npm
* Bumping to 1.0.0
> Bumped task buffer to v4

- deno.json
- timebox/README.md
- timebox/deno.json
- timebox/mod.ts
- timebox/timebox.test.ts
Adding time constraints to any operation without having to change it at all is one of the most powerful demonstrations of how Effection composes. It is also needed to implement convergent assertions which we will need in many different locations, and which we may want to release as a library in of itself.
This takes the essence of all the timeout implementations over the last 5 years and puts them into generally available "timebox" package. A key decision that makes this implementation more flexible than earlier implementations is it does not throw a "TimeoutError" when the operation exceeds the deadline. Rather, it returns a discriminated union indicating whether it completed successfuly, or if it timed out.
> 🎉 Add @effection-contrib/timebox

- README.md
- deno-deploy/README.md
- fx/README.md
- task-buffer/README.md
- tinyexec/README.md
- websocket/README.md
I'm setting up search and I want to have consistent results for contributing package names.
1. Use a consistent h1 in the readmes
2. Enchanged websocket readme with Claude.ai
> Clean up Readme titles

- deno.json
- tasks/publish-matrix.ts
https://github.com/thefrontside/effection-contrib/actions/runs/13056241575/job/36427891448 failed because in #50, I also deleted files needed by `tasks/publish-matrix.ts` which is used by the publish workflow.
Cleaned up the script and added the missing bits.
> Fix publish matrix

- .github/workflows/verify.yaml
- tasks/build-npm.ts
- tasks/publish-matrix.ts
#51 failed because I missed build-npm.ts script
Added step to verify workflow to test types in tasks
Fixed import in build-npm
> Fix built npm

- tasks/publish-matrix.ts
3rd time is the charm. #52 failed because #51 didn't remove './' from workspace.
Removed the prefix and simplified the script a bit more.
> Removed './' prefix from workspace and cleaned up

- tasks/build-npm.ts
- tasks/lib/read-packages.ts
- tasks/publish-matrix.ts
3rd time was not the charm. I don't know what happened to this build script, but it was all kinds of out of wack.
- Moved shared code into a different module to prevent publish-matrix.ts from being evaluated.
- Reorganized the build script
> Moved shared code into another module

- worker/worker.ts
MDX evaluates JSDOC content as JS and it struggles to parse content in `{/* reference in here get confused */}` . We'll need to figure out how to fix this in effection-www.
Just removed a reference that caused problems.
> Remove reference to WorkerOptions

- deno.json
- test-adapter/README.md
- test-adapter/deno.json
- test-adapter/mod.ts
- test-adapter/test/adapter.test.ts
It's nice to be able to use Effection operations as the native currency of your tests since it lets you use all the Effection-y goodness like contexts, resources, etc.. right inside your tests!
This provides a test adapter that can be used to integrate with various testing frameworks out there. It isn't meant to be used by itself so much as to be used by framework integrations. This is an extraction of the `TestAdapter` written to integrate with vitest.
> Test Adapter

- watch/main.ts
Apparently, no top level awaits are allowed in cjs modules.
> remove top level await in main module

- watch/watch.ts
Mdx doesn't like `{Result<Promise>}`. 
Use backticks for now until I figure it out.
> Use backticks for now

- raf/README.md
- raf/raf.ts
There were a few details that can be added to improve understanding.
- While streams are most often implemented with resources, it is not always the case, and in any event it is an implementation detail, so remove the reference to them.
- link to the RAF docs.
- in the raf docs, they refer to the parameter pass to the callback as a `timestamp`. This adjusts the docs to use that terminology in stead.
> Fixup the RAF docs

- deno.json
- jsonl-store/deno.json
- jsonl-store/jsonl.test.ts
- raf/deno.json
- raf/raf.test.ts
- signals/array.test.ts
- signals/helpers.test.ts
- stream-helpers/batch.test.ts
- stream-helpers/deno.json
- stream-helpers/filter.test.ts
- stream-helpers/map.test.ts
- stream-helpers/mod.test.ts
- stream-helpers/test-helpers/faucet.test.ts
- stream-helpers/tracker.test.ts
- stream-helpers/valve.test.ts
- tasks/build-npm.ts
- tasks/lib/read-packages.ts
- tasks/publish-matrix.ts
- test-adapter/deno.json
- test-adapter/test/adapter.test.ts
- watch/deno.json
- watch/test/watch.test.ts
- watch/watch.ts
#88 is failing because Deno 2.5 now recommends using imports in deno.json instead of inline specifiers.
Moved all specifiers into imports
> Eliminted all specifiers in ts files

- test-adapter/deno.json
I want to start pulling out changes from #87 to make it mergable. I need test-adapter to be on v3 so I can use it as a dependency with deno-testing-bdd package that I'll publish next.
Switch to v3 and bump minor to 0.3.0
> Downgrade effection to 3 in test-adapter

- bdd/deno.json
`@effectionx/bdd` didn't publish because license was missing.
Add missing license
> Add license to @effectionx/bdd

- bdd/deno.json
The `addOnetimeSetup()` method was only added in 0.5.0 so we have to depend on that version.
> ⬆️ Update bdd dependency on @effectionx/test-adapter
